# Jekyll Resume Theme

# Site settings
title: Mayank Agarwal
email: mayankgrwl97@gmail.com
description: Jekyll Resume is a mega simple resume theme for Jekyll.
baseurl: ""
url: "http://mayankgrwl97.github.io/mayankagarwal"
name: Mayank Agarwal
job: Computer Science Undergraduate
location: BITS Pilani, INDIA
languages: HTML, CSS and Javascript
twitter_username: mayankgrwl97
medium_username: mayankgrwl97
github_username:  mayankgrwl97
linkedin_username:  mayankgrwl97
spoj_username: mayankgrwl97
email_address: mayankgrwl97@gmail.com
contact: +91 7073836075
# Build settings
markdown: kramdown
